// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSvgMorph = require("react-svg-morph");

function make(width, height, duration, viewBox, rotation, preserveAspectRatio, children) {
  return ReasonReact.wrapJsForReason(ReactSvgMorph.MorphReplace, {
              width: width,
              height: height,
              duration: duration,
              viewBox: viewBox,
              rotation: rotation,
              preserveAspectRatio: preserveAspectRatio
            }, children);
}

var MorphReplace = /* module */[/* make */make];

exports.MorphReplace = MorphReplace;
/* ReasonReact Not a pure module */
